name: Create Bicep template release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release and upload assets
    steps:
    - name: Checkout repo
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

    - name: Create Bicep template release package
      run: zip -r ${{ github.event.repository.name }}.zip . -x ".git/*" ".github/*" ".gitignore"

    - name: Determine if pre-release
      id: check_version
      run: |
        TAG_NAME="${{ github.ref_name }}"
        # Check if the tag name ends with "-pre"
        if [[ "$TAG_NAME" == *"-pre" ]]; then
          echo "::notice::Detected specific pre-release suffix '-pre' for tag: $TAG_NAME"
          echo "::set-output name=is_prerelease::true"
        else
          echo "::notice::Tag does not end with '-pre': $TAG_NAME"
          echo "::set-output name=is_prerelease::false"
        fi
      shell: bash

    - name: Create Bicep template release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ github.ref_name }}
        IS_PRERELEASE: ${{ steps.check_version.outputs.is_prerelease }}
      run: |
        RELEASE_FLAGS="--generate-notes"
        
        if [ "$IS_PRERELEASE" = "true" ]; then
          echo "Creating a pre-release for $TAG"
          RELEASE_FLAGS="$RELEASE_FLAGS --prerelease"
        else
          echo "Creating a standard release for $TAG"
          RELEASE_FLAGS="$RELEASE_FLAGS --latest"
        fi

        # Create the release using gh CLI with dynamic flags
        gh release create "$TAG" ./${{ github.event.repository.name }}.zip $RELEASE_FLAGS